# Homework Wk5 - D22

In [6]:
# import self developed simplex method
from simplex import *
import pandas as pd

## Example

Consider the following LP:

$$
\begin{array}{ll}
\max \ z = & 5 x_1 + 2 x_2 \\
\text{s.t.} \\
& x_1 + x_2 \le 6 \\
& x_1 - x_2 \le 0 \\
& x_1, x_2 \ge 0
\end{array}
$$


In [13]:
# LP matrix setup
c = [5, 2]
b = [6, 0]
A = [[1, 1], [1, -1]]

In [16]:
# convert to the augmented matrix
init_tab = init_tab_standard_lp(A, b, c)
print(pd.DataFrame(init_tab))

     0    1    2    3    4    5
0  1.0 -5.0 -2.0 -0.0 -0.0 -0.0
1  0.0  1.0  1.0  1.0  0.0  6.0
2  0.0  1.0 -1.0  0.0  1.0  0.0


In [17]:
# solve the LP problem manually
M_mat = init_tab.copy()
row_n, col_n = M_mat.shape - np.array([1, 2])  # number of constraints and number of variables
pivot_col = 1 # the most negative value in the first coeffient row
ratio_list = np.divide(M_mat[range(1, row_n + 1), -1], M_mat[range(1, row_n + 1), pivot_col])
print('ratio list:', ratio_list)
pivot_row = min_ratio_test(ratio_list)
print('pivot row:', pivot_row)


ratio list: [6.00 0.00]
pivot row: 2


The above example is a simple degenerate LP problem. It is unsolved.

## Example

Consider the following LP.
$$\begin{array}
{ll}
\max z = & 5 x_1 + x_2 + 3x_3 + 4x_4 \\
s.t.\\
& x_1 - 2 x_2 + 4x_3 + 3x_4 \le 20 \\
& -4x_1 + 6x_2 + 5x_3 - 4x_4 \le 40 \\
& 2 x_1 - 3x_2 + 3x_3 + 8 x_4 \le 50\\
& x_i \ge 0.
\end{array}
$$
Work through the simplex and show that it's unbounded.

In [7]:
# setup
c = [5, 1, 3., 4]
b = [20., 40, 50]
A = [[1., -2, 4, 3], [-4, 6, 5, -4], [2, -3, 3, 8]]

In [8]:
init_tab = init_tab_standard_lp(A, b, c)
print(pd.DataFrame(init_tab))

     0    1    2    3    4    5    6    7     8
0  1.0 -5.0 -1.0 -3.0 -4.0 -0.0 -0.0 -0.0  -0.0
1  0.0  1.0 -2.0  4.0  3.0  1.0  0.0  0.0  20.0
2  0.0 -4.0  6.0  5.0 -4.0  0.0  1.0  0.0  40.0
3  0.0  2.0 -3.0  3.0  8.0  0.0  0.0  1.0  50.0


In [9]:
tab = init_tab.copy()
simplex_solver(tab, display=1)

3 constraints and 7 variables
pivot columns are: [5, 6, 7]
initial tableau is:
     0    1    2    3    4    5    6    7     8
0  1.0 -5.0 -1.0 -3.0 -4.0 -0.0 -0.0 -0.0  -0.0
1  0.0  1.0 -2.0  4.0  3.0  1.0  0.0  0.0  20.0
2  0.0 -4.0  6.0  5.0 -4.0  0.0  1.0  0.0  40.0
3  0.0  2.0 -3.0  3.0  8.0  0.0  0.0  1.0  50.0
pivot columns are: [1, 6, 7]
new pivot is (1, 1)
     0    1     2     3     4    5    6    7      8
0  1.0  0.0 -11.0  17.0  11.0  5.0  0.0  0.0  100.0
1  0.0  1.0  -2.0   4.0   3.0  1.0  0.0  0.0   20.0
2  0.0  0.0  -2.0  21.0   8.0  4.0  1.0  0.0  120.0
3  0.0  0.0   1.0  -5.0   2.0 -2.0  0.0  1.0   10.0
pivot columns are: [1, 6, 2]
new pivot is (3, 2)
     0    1    2     3     4     5    6     7      8
0  1.0  0.0  0.0 -38.0  33.0 -17.0  0.0  11.0  210.0
1  0.0  1.0  0.0  -6.0   7.0  -3.0  0.0   2.0   40.0
2  0.0  0.0  0.0  11.0  12.0   0.0  1.0   2.0  140.0
3  0.0  0.0  1.0  -5.0   2.0  -2.0  0.0   1.0   10.0
pivot columns are: [1, 3, 2]
new pivot is (2, 3)
     0   

/Users/qsong/Documents/GitHub/foo1/src/simplex.py:56: RuntimeWarning: divide by zero encountered in divide
  ratio_list = np.divide(M_mat[range(1, row_n + 1), -1], M_mat[range(1, row_n + 1), pivot_col])


## Example
Consider the following LP:
$$\begin{array}
{ll}
\max z = & x_1 + x_2 + x_3 + x_4 \\
s.j. \\
& x_1 + x_2 \le 3\\
& x_3 + x_4 \le 2\\
& x_i \ge 0.
\end{array}
$$
Work through the simplex and find all the optimal bfs.

In [32]:
# setup
c = [1.]*4
b = [3., 2]
A = [[1., 1, 0, 0],
     [0, 0, 1., 1]]

In [35]:
init_tab = init_tab_standard_lp(A, b, c)
print(pd.DataFrame(init_tab))

     0    1    2    3    4    5    6    7
0  1.0 -1.0 -1.0 -1.0 -1.0 -0.0 -0.0 -0.0
1  0.0  1.0  1.0  0.0  0.0  1.0  0.0  3.0
2  0.0  0.0  0.0  1.0  1.0  0.0  1.0  2.0


In [34]:
tab = init_tab
simplex_solver(tab, display=1)

2 constraints and 6 variables
pivot columns are: [5, 6]
initial tableau is:
[[1.00 -1.00 -1.00 -1.00 -1.00 -0.00 -0.00 -0.00]
 [0.00 1.00 1.00 0.00 0.00 1.00 0.00 3.00]
 [0.00 0.00 0.00 1.00 1.00 0.00 1.00 2.00]]
pivot columns are: [1, 6]
new pivot is (1, 1)
[[1.00 0.00 0.00 -1.00 -1.00 1.00 0.00 3.00]
 [0.00 1.00 1.00 0.00 0.00 1.00 0.00 3.00]
 [0.00 0.00 0.00 1.00 1.00 0.00 1.00 2.00]]
pivot columns are: [1, 3]
new pivot is (2, 3)
[[1.00 0.00 0.00 0.00 0.00 1.00 1.00 5.00]
 [0.00 1.00 1.00 0.00 0.00 1.00 0.00 3.00]
 [0.00 0.00 0.00 1.00 1.00 0.00 1.00 2.00]]
pass the optimal test
optimal value is 5.0
The final tableau is 
 [[1.00 0.00 0.00 0.00 0.00 1.00 1.00 5.00]
 [0.00 1.00 1.00 0.00 0.00 1.00 0.00 3.00]
 [0.00 0.00 0.00 1.00 1.00 0.00 1.00 2.00]]


Pivot columns in the final tableau are 1 and 3.
- optimal solution is
     $$x = (3, 0, 2, 0).$$

Non-pivot columns are $$2, 4, 5, 6.$$
Since the corresponding entries of row 0 is $$0, 0, 1, 1$$
this means there is zero coefficient to the NBV.

This means, by pivoting w.r.t. column 2 or 4, we can find another

- pivoting with column 2, new pivot columns are 2 and 3, and optimal solution is $$x = (0, 3, 2, 0)$$
- pivoting with column 4, new pivot columns are 1 and 4, and optimal solution is $$x = (3, 0, 0, 2)$$
- similarly, another optimal solution is $$x = ( 0, 3, 0, 2)$$